### ISSUE TITLE
Disallow public key in private key

### ISSUE THREAD

**Issue by bwesterb** [lamps-wg/kyber-certificates#60]
When "unpacking" the seed, you immediately get the expanded private and public key. Thus allowing a public key in the private key is redundant. I think we should disallow it. @seanturner WDYT?

_Originally posted by @bwesterb in https://github.com/lamps-wg/kyber-certificates/issues/59#issuecomment-2427595844_

**Comment by dconnolly** [comment]
Agreed

**Comment by seanturner** [comment]
I think disallow might be strong.  I can get behind a SHOULD and they say why you don't need to and then only people who want to use the footgun do so.

**Comment by seanturner** [comment]
@danvangeest PTAL

**Comment by bwesterb** [comment]
> I think disallow might be strong. I can get behind a SHOULD and they say why you don't need to and then only people who want to use the footgun do so.

In ML-KEM the expanded private key contains the public key, which is required for decapsulation. At the very least we need to add language that the included public key cannot be used in decapsulation. I expect there would be some requests for checks on whether the public key matches the private key to some degree. One could for instance ask that the user checks whether the `rho` value (the seed of the lattice) matches between the included public key and seed, as a sanity check. That adds complexity down the line for implementations to implement those checks and linters to check whether that check is performed. As computing the expanded key pair from the seed is cheap, one could just require the included public key to match the seed completely. But then: what is the point?
