### ISSUE TITLE
Security Considerations

### ISSUE THREAD

**Issue by seanturner** [lamps-wg/kyber-certificates#62]
Do we just refer to the [ML-KEM Security Considerations](https://datatracker.ietf.org/doc/draft-sfluhrer-cfrg-ml-kem-security-considerations/) and call it quits?

**Comment by danvangeest** [comment]
I think the security considerations should justify the choice of storing the 64-byte seed as providing the MAL-BIND-K-CT property.  While not explicit, section 3.1 of https://eprint.iacr.org/2024/523.pdf gives the justification.  That section suggests removing the hash value from the longer serialized format.  Implicitly, by using the shorter 64-byte seed format the hash has been removed.

It may also be worth noting that the 64-byte encoding does not achieve MAL-BIND-K-PK, but a protocol can achieve this property by binding the public key to the ML-KEM shared secret by feeding them both into a KDF.

**Comment by bwesterb** [comment]
As an aside, it's not just these binding properties. There are two other clear advantages of using the seed: 1. it simplifies implementation complexity as we don't have to think or worry about private key validation, and 2. it saves a lot of space.

**Comment by bwesterb** [comment]
Maybe it's better to include a more detailed discussion of that in Scott's draft.

**Comment by dconnolly** [comment]
Agree with Scott and Bas; a more expanded Security Considerations section in this document does not preclude the other document, or expanding the other document too

**Comment by dconnolly** [comment]
Also Scott's document hasn't been adopted yet
